server:
  tomcat:
    mbeanregistry:
      enabled: true   # actuator에서 tomcat.threads.xxx 메트릭을 확인하기 위한 옵션

management:
  endpoints:
    web:
      exposure:
        include: '*'    # 모든 Actuator 엔드포인트를 노출한다
  metrics:
    enable.all: true
    enable.tomcat: true
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true